### ISSUE TITLE
gpg: signing failed: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by craftyphotons** [goreleaser/goreleaser-action#201]
In attempting to use the GPG signing functionality as documented with the use of crazy-max/ghaction-import-gpg I can't seem to find a way around the following error when GoReleaser gets to the signing pipe:

```
      • signing                   cmd=[gpg --batch -u BF9DE7B4E2AD83A41CFD7713280CAB053A042287 --output dist/protomy-v0.0.0-SNAPSHOT-c05f10f-checksums.txt.sig --detach-sign dist/protomy-v0.0.0-SNAPSHOT-c05f10f-checksums.txt]
      • gpg: signing failed: Inappropriate ioctl for device
```

_(See [here](https://github.com/protomy/protomy/runs/690463886?) for the full action log)_

I've been comparing back and forth between [my own GitHub workflow configuration](https://github.com/protomy/protomy/blob/master/.github/workflows/release.yaml#L40-L48) and the one in use by this repository's own [CI workflow](https://github.com/goreleaser/goreleaser-action/blob/master/.github/workflows/ci.yml#L88-L95), but can't seem to spot any differences between the two that could lead to this error, which has been confounding given that the CI workflow for goreleaser/gorelease-action itself is passing, with virtually the same configuration other than the key itself.

Seems as though there's been a similar issue referenced elsewhere in https://github.com/actions/runner/issues/241#issuecomment-556556163 but again that would be confusing given that the workflow is passing in the GoReleaser action's own tests 😄

**Comment by crazy-max** [comment]
Hi @craftyphotons, this is because you `export GPG_TTY`. Remove this step and it should be ok.

**Comment by craftyphotons** [comment]
Unfortunately it's still occurring even with that step removed: https://github.com/protomy/protomy/runs/690511183

**Comment by crazy-max** [comment]
Ok how do you export your GPG key? Do you follow the [Prerequesites](https://github.com/crazy-max/ghaction-import-gpg#prerequisites)?

**Comment by craftyphotons** [comment]
Yep! I even re-followed everything just now to be sure, and reuploaded secrets with the keys `GPG_PRIVATE_KEY` and `PASSPHRASE` instead of the names I formerly had for them.

https://github.com/protomy/protomy/runs/690545899

I included an additional step as you show in the documentation to echo out the GPG key/user information to verify that the gpg import action is working appropriately.

The only difference I can ascertain at this point is that your build from a couple days ago ran against version [20200430.1](https://github.com/actions/virtual-environments/blob/ubuntu18/20200430.1/images/linux/Ubuntu1804-README.md) of `ubuntu-latest` and mine is running against [20200512.2](https://github.com/actions/virtual-environments/blob/ubuntu18/20200512.2/images/linux/Ubuntu1804-README.md), so perhaps there was some sort of regression there in GitHub's Ubuntu environment.

I'm also getting the error on `macos-latest` though: https://github.com/protomy/protomy/runs/690567394

**Comment by crazy-max** [comment]
I have a re-run of the [CI workflow](https://github.com/goreleaser/goreleaser-action/runs/690558997?check_suite_focus=true#step:1:8) and everything works fine.
I will take a closer look on this. Keep you in touch.

**Comment by craftyphotons** [comment]
Thanks @crazy-max — definitely must be something with my key then. I'll dig into it from my side some more and see if I can narrow things down more.

**Comment by crazy-max** [comment]
@craftyphotons Can you test with `uses: crazy-max/ghaction-import-gpg@pinentry-loopback` ?

**Comment by craftyphotons** [comment]
![image](https://user-images.githubusercontent.com/17915374/82390599-20935400-9a0d-11ea-9253-0c4f2f767da5.png)

**Comment by craftyphotons** [comment]
FWIW I just took a look at that branch and looks like you're doing the same thing that I attempted a bit ago:

![image](https://user-images.githubusercontent.com/17915374/82390765-97305180-9a0d-11ea-876a-056cc290e4db.png)

(The `OK` in the output of the first step is from me bouncing the GPG agent)

Which unfortunately still yielded the same result.

**Comment by crazy-max** [comment]
@craftyphotons Ok thanks for your feedback. I've made some new changes, can you try it?

**Comment by craftyphotons** [comment]
No dice still but something different this time!

![image](https://user-images.githubusercontent.com/17915374/82394287-9fd95580-9a16-11ea-9824-8fcf6940f537.png)

**Comment by crazy-max** [comment]
Ok this is what I tought. It looks like your GPG key requires a special input which is not allowed in batch mode. Could you give me more information on how you created the key? In particular the version of GnuPG used to create the key.

Can you also try creating a key following [those steps](https://help.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key) of GitHub.

**Comment by craftyphotons** [comment]
I think I just came to the same conclusion myself by creating a new key here on my laptop, which worked.

However now the mystery deepens, as the non-working key was created on a different machine with the same procedure and the same `gpg.conf`!

Here's the `gpg.conf` that's on both machines:

```
# Avoid information leaked
no-emit-version
no-comments
export-options export-minimal

# Displays the long format of the ID of the keys and their fingerprints
keyid-format 0xlong
with-fingerprint

# Displays the validity of the keys
list-options show-uid-validity
verify-options show-uid-validity

# Limits the algorithms used
personal-cipher-preferences AES256
personal-digest-preferences SHA512
default-preference-list SHA512 SHA384 SHA256 RIPEMD160 AES256 TWOFISH BLOWFISH ZLIB BZIP2 ZIP Uncompressed

cipher-algo AES256
digest-algo SHA512
cert-digest-algo SHA512
compress-algo ZLIB

disable-cipher-algo 3DES
weak-digest SHA1

s2k-cipher-algo AES256
s2k-digest-algo SHA512
s2k-mode 3
s2k-count 65011712
```

Both machines are also running gpg 2.2.17.

In any case though, sounds like I'm probably an odd edge case here... I'll keep trying to determine how the key on the other machine might be different though and let you know if I find anything.

Thanks a lot for spending the time to help me track this down!

**Comment by crazy-max** [comment]
Thanks, don't hesitate to come back to me, I close this issue in the meantime.

**Comment by StephenWithPH** [comment]
I'm throwing a breadcrumb here for future searchers... a key generated with GPG2 gave me the same error. Using a key generated by GPG1 worked just fine. https://github.com/actions/runner/issues/241#issuecomment-556556163 was helpful in figuring this out.

**Comment by OJFord** [comment]
@crazy-max I have the same issue with an RSA 4096 bit signing key generated with `GNUPGHOME="$(mktemp -d)" gpg`; where `gpg --version` is 2.2.29, using ghaction-import-gpg@v4.1.0 and goreleaser-action@v2.
