### ISSUE TITLE
Cannot point gorelease to subdirectory: "not a git repository (or any of the parent directories)"

### ISSUE THREAD

**Issue by fbiville** [goreleaser/goreleaser-action#223]
I am currently struggling to configure goreleaser Github action to point to a subdirectory.
I have tried many combinations but nothing seems to work.

The `goreleaser` configuration file is under the `./plugins/vsphere` folder of this [repository](https://github.com/fbiville/sources-for-knative/tree/issue_60_login).
The release script is [here](https://github.com/fbiville/sources-for-knative/blob/ecfb6b120222054804de0d2b39d4b7e78cf9010c/.github/workflows/release.yaml#L93-L100).

How do I configure a relative path to the repository so that Goreleaser works? Thanks!

**Comment by crazy-max** [comment]
Hi @fbiville,

* You defined a [workdir](https://github.com/fbiville/sources-for-knative/blob/ecfb6b120222054804de0d2b39d4b7e78cf9010c/.github/workflows/release.yaml#L98) that does not contain any `.goreleaser.yml` definition.
* [`args`](https://github.com/fbiville/sources-for-knative/blob/ecfb6b120222054804de0d2b39d4b7e78cf9010c/.github/workflows/release.yaml#L97) is not properly used. Remove `./plugins/vsphere` from there.
* `go.[mod|sum]` is missing in your [plugins/vsphere](https://github.com/fbiville/sources-for-knative/tree/ecfb6b120222054804de0d2b39d4b7e78cf9010c/plugins/vsphere) folder.

Beyond the points I give above, I don't understand your workflow. What do you want to build? The project at the root? or just the "plugin"? Have you first tested locally?

**Comment by fbiville** [comment]
I just want to release the sources of `./plugins/vsphere` but the `go.{mod,sum}` is defined at the top level. Does that setup make sense for goreleaser?

**Comment by crazy-max** [comment]
What's the purpose to [clone in a gopath-style-folder](https://github.com/fbiville/sources-for-knative/blob/ecfb6b120222054804de0d2b39d4b7e78cf9010c/.github/workflows/release.yaml#L81) if you are using go modules?

And also have you first tried using goreleaser locally before this GitHub Action?

**Comment by fbiville** [comment]
@crazy-max it's my first time contributing to this repository, so I do not have the context on this. I just kept the changes to a minimum.

**Comment by fbiville** [comment]
I'd assume https://github.com/google/ko is historically biased towards GOPATH (and existed before the introduction of Go modules) but I'm not entirely sure.

**Comment by fbiville** [comment]
I tried this change before but the same error happens [when I point `workdir` to the plugin folder](https://github.com/fbiville/sources-for-knative/blob/07b03dde4daf54e48eec8fc66b0f574164346c0c/.github/workflows/release.yaml#L98):
```
##[error]fatal: not a git repository (or any of the parent directories): .git
```
Which is strange because `.git` is located just two levels above the `workdir` location.

I also tried an absolute path with `${{ github.workspace }}/src/github.com/${{ github.repository }}/plugins/vpshere` and a relative path with just `./plugins/vpshere`. I end up with the same error.

I can understand if the Go setup is now what goreleaser expects. I'm just confused by the Git error message (after all, a parent folder contains `.git`).

**Comment by crazy-max** [comment]
@fbiville 

For me if `sources-for-knative` is the main project then `./plugins/vpshere` should be a dedicated repo and not a subdir. But if you really want this structure, `.goreleaser.yml` should be at root level of `sources-for-knative` with several [build steps](https://goreleaser.com/customization/build/) (one for main project and one per plugin).

> so I do not have the context on this. I just kept the changes to a minimum.

So before using the GitHub action, please test it locally on your computer first. And come back later with an implementation through this GitHub Action.

> `##[error]fatal: not a git repository (or any of the parent directories): .git`

AFAIK this use case is not compatible with GoReleaser. A hint @caarlos0?

**Comment by fbiville** [comment]
Just to clarify: `goreleaser` will only be used for the plugin, not the main project. So that would mean a single build step, right?

**Comment by crazy-max** [comment]
@fbiville 

> So that would mean a single build step, right?

Yes something like:

```yaml
builds:
  -
    main: ./plugins/vsphere/cmd/vsphere/main.go
    ...
```

**Comment by fbiville** [comment]
> So before using the GitHub action, please test it locally on your computer first. And come back later with an implementation through this GitHub Action.

After a few changes, I managed to get `goreleaser` run locally and successfully:
```shell
export GITHUB_TOKEN=xxx; goreleaser

   • releasing...
   • loading config file       file=.goreleaser.yml
// [...]
         • token type                type=github
      • scoop manifests
         • token type                type=github
         • pipe skipped              error=scoop section is not configured
   • release succeeded after 68.17s
```

The Github action still fails with the same error.

**Comment by caarlos0** [comment]
judging by the error log:

```
##[error]fatal: not a git repository (or any of the parent directories): .git
```

seems to be something on the action itself, not on goreleaser (you can see goreleaser didn't even start running) 🤔

---

maybe the action (or some dep) checks for a `.git` folder? If so, that's not ideal, should do something [like this](https://github.com/goreleaser/goreleaser/blob/master/internal/git/git.go#L14) instead...

**Comment by crazy-max** [comment]
@caarlos0 

> maybe the action (or some dep) checks for a .git folder? If so, that's not ideal, should do something like this instead...

Thanks will check this out.

**Comment by crazy-max** [comment]
@fbiville Ok found out you're using `goreleaser/goreleaser-action@v1`. Try this instead:

```yaml
  kn-vsphere:
    name: Release vSphere Knative plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by fbiville** [comment]
I swear I tried `goreleaser/goreleaser-action@v2` and it did not work 🤔 
Now it works like a charm! Thanks!
