### ISSUE TITLE
error: "compile: version 'go1.14.7' does not match go tool version 'go1.15'" when using go 1.15

### ISSUE THREAD

**Issue by ggilmore** [goreleaser/goreleaser-action#241]
I received the following error when trying to run goreleaser with go 1.15 installed in the CI environment: 

```
...
# runtime/internal/sys
compile: version "go1.14.7" does not match go tool version "go1.15"
...
```

Full logs from that failed run: https://github.com/sourcegraph/ds-to-dhall/runs/1038865701?check_suite_focus=true#step:6:59

---

Downgrading to go 1.14.7 "fixed" the issue. See:

- Full logs from run: https://github.com/sourcegraph/ds-to-dhall/runs/1038936094?check_suite_focus=true#step:6:1
- Commit: https://github.com/sourcegraph/ds-to-dhall/commit/f98e0ec589f625ed48456b2c53db163a97bea8a4

**Comment by crazy-max** [comment]
@ggilmore Golang is not properly installed on the runner. You should use the official [setup-go](https://github.com/actions/setup-go) action.
