### ISSUE TITLE
`  The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/`

### ISSUE THREAD

**Issue by moul** [goreleaser/goreleaser-action#247]
Hi :wave:,

When running actions using goreleaser-action, I get this warning message:

    The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

![Screenshot - Manfred 2020-10-07 at 17 16 15](https://user-images.githubusercontent.com/94029/95350820-e0037c80-08c0-11eb-9af8-96180d2b4d24.png)

---

From what I can see, it should come from this: https://github.com/goreleaser/goreleaser-action/blob/9593cd0a2026bfb689d6d8a19c9d735b6ed8caaa/dist/index.js#L404

I would be happy to contribute but I don't have experience in GitHub actions and I will take some time, except maybe if someone can help me be onboarded on this project?

Thank you for this project :+1:

**Comment by crazy-max** [comment]
Hi @moul, [v2.2.1 / v2](https://github.com/goreleaser/goreleaser-action/releases/tag/v2.2.1) actually fixes this issue. Can you give me a link to your workflow?

**Comment by crazy-max** [comment]
@moul Ok I've found [your repo](https://github.com/berty/berty) and this is not the goreleaser-action that [triggers this warning](https://github.com/berty/berty/runs/1227242522?check_suite_focus=true#step:5:46) but `codfish/semantic-release-action@v1`.
