### ISSUE TITLE
Feature request: non-tag "release" to actions artifacts

### ISSUE THREAD

**Issue by eriksw** [goreleaser/goreleaser-action#254]
It'd be nice if there was a way to have goreleaser create artifacts for PRs (and other non-tag runs) but instead of pushing an actual github release, it just uploads the artifacts to the actions run like `actions/upload-artifact`.

This would be particularly useful when working on cgo-requiring projects where building locally is annoying. (Push a branch, wait for action to run, get artifacts from the actions run.)

I have a hunch this _might_ be possible without code changes, in which case please treat this issue as a request for an example workflow yaml. :)

**Comment by crazy-max** [comment]
@eriksw #257
