### ISSUE TITLE
GORELEASER_CURRENT_TAG is not respected with v2.4

### ISSUE THREAD

**Issue by spirosoik** [goreleaser/goreleaser-action#260]
This seems to break the functionality. https://github.com/goreleaser/goreleaser-action/pull/259

Reference comment https://github.com/goreleaser/goreleaser-action/pull/259#issuecomment-736770715

**Comment by crazy-max** [comment]
@spirosoik I would need some logs please. Thanks.

**Comment by spirosoik** [comment]
I will try to see how I can redact a few stuff

**Comment by stack72** [comment]
Hi 

I am seeing the same issue. Our builds are public so I can share the links...

You can see the GORELEASER_CURRENT_TAG being set to GITHUB_ENV here - https://github.com/pulumi/pulumi-azure/runs/1475650624?check_suite_focus=true#step:9:2

You can then see that available as an environment variable here - https://github.com/pulumi/pulumi-azure/runs/1475650624?check_suite_focus=true#step:10:32

But you can see that it hasn't respected that value - https://github.com/pulumi/pulumi-azure/runs/1475650624?check_suite_focus=true#step:10:43

**Comment by crazy-max** [comment]
@stack72 In your case it looks like you handle GORELEASER_CURRENT_TAG yourself so the action overwrites it. I will push a fix for that. Maybe it will fix the current issue too.

**Comment by stack72** [comment]
This is something we've been doing for months and just stopped working recently so I assumed it was the same thing - maybe not though

Thank you so much for pinging back on this!

**Comment by crazy-max** [comment]
@stack72 I've pushed a fix, can you test?

**Comment by stack72** [comment]
> @stack72 I've pushed a fix, can you test?

Testing it now - will update you on how it goes! thank you :)

**Comment by stack72** [comment]
> > @stack72 I've pushed a fix, can you test?
> 
> Testing it now - will update you on how it goes! thank you :)

Worked a treat @crazy-max - thank you!
