### ISSUE TITLE
Unable to create first release

### ISSUE THREAD

**Issue by miniscruff** [goreleaser/goreleaser-action#262]
I am trying to get my first release going and I think the order in which operations are handled is causing publishing to be skipped no matter what. https://github.com/miniscruff/changie/runs/1586648055?check_suite_focus=true

From the logs:
```
✅ GoReleaser version found: v0.149.0
⬇️ Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.149.0/goreleaser_Linux_x86_64.tar.gz...
📦 Extracting GoReleaser...
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/12b4050d-0926-4d1f-8daa-4096fc877af9 -f /home/runner/work/_temp/fe7bcb1f-0fc6-4e18-b453-94ddef55c73f
✅ GoReleaser installed successfully
⚠️ No tag found for commit 'e152889'. Snapshot forced
🏃 Running GoReleaser...
/opt/hostedtoolcache/goreleaser-action/0.149.0/x64/goreleaser release --rm-dist --skip-validate --release-notes=changes/v0.1.0.md --snapshot
   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • releasing v0.1.0, commit e152889fab61ac26f2a32daac1d34ef3cdd622c7
      • pipe skipped              error=disabled during snapshot mode
   • parsing tag      
```

I am using a separate release file and tag, however, because the project is new I do not have any existing tags and thus the snapshot flag is forced. This means my project never gets published. The tag is later read from the environment variables but by then it is too late. I tried adding `--skip-validate` but it seems snapshot has higher precendence. 

Repro steps should be:
1. Create new repo
2. Add goreleaser
3. Specify tag and release notes file
4. Build will never publish

**Comment by miniscruff** [comment]
I was able to get around this by adding a tag I didn't care about and then using the install only option for the action followed by a goreleaser command. Not quite ideal but it does work.

**Comment by crazy-max** [comment]
@miniscruff See https://github.com/goreleaser/goreleaser-action/issues/121#issuecomment-640108212
