### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by hazcod** [goreleaser/goreleaser-action#265]
Hi, any idea how to use the Action to do cross-compilation?
In regards to https://github.com/hazcod/enpass-cli/issues/97

Ref https://github.com/hazcod/enpass-cli/blob/master/.github/workflows/release.yml#L56

**Comment by crazy-max** [comment]
@hazcod Not with this action you have to use a dedicated Docker image. See https://goreleaser.com/cookbooks/cgo-and-crosscompiling/ and https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-a-docker-hub-action to use a Docker image as an action step.
