### ISSUE TITLE
Requirement of GITHUB_REF causing limitations

### ISSUE THREAD

**Issue by abatilo** [goreleaser/goreleaser-action#27]
Hi all,

The change to require a GITHUB_REF for the action to run is causing some inconveniences that will limit adoption of this action.

If you want GITHUB_REF to be populated with a tag, the action trigger event needs to be something like `on: create` or `on: release` which is usually fine.

The problem is, if you're using another project to manage your tags and releases like https://github.com/semantic-release/github, then those tag events are created (by default) using the default GH Action token.

This GH Action Token is special in that it does NOT trigger other events as to avoid an infinite loop. This is an explicit feature/decision by the GH Actions team.

This means that I couldn't have semantic-release run as one workflow to trigger the goreleaser workflow, but ideally no human is the one pushing tags.

This leaves us with one of two options:

You could create a personal access token for whatever flow is pushing tags. Since it's a PAT, the `on: release` and `on: create` workflows will trigger. This is not ideal because now you have to create a PAT which means you have to tie that execution to a person. Since there's no way to create organizational access tokens, you'll have to create another user to be a service user in GitHub which could cost you money.

The second option is to install goreleaser directly to the GitHub Action Runner itself like so:
```
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -Lo /tmp/goreleaser.tar.gz https://github.com/goreleaser/goreleaser/releases/download/v0.120.3/goreleaser_Linux_x86_64.tar.gz
        tar -xzvf /tmp/goreleaser.tar.gz -C /tmp/
        /tmp/goreleaser release
```

This is not ideal because now I'm coupled to expectations of what is installed in the Runner environment, instead of getting an isolated container to run in.

Could we remove the requirement of a GITHUB_REF?

**Comment by crazy-max** [comment]
Hi @abatilo,

> The **change** to require a GITHUB_REF

What change? This action has worked as follows since its inception.

> Could we remove the requirement of a GITHUB_REF?

`GITHUB_REF` is not required to use this action. In fact `goreleaser` requires a git tag to work but to allow developers to test their workflow and also contributors to use it through PRs, this action [adds the `--snapshot` tag](https://github.com/goreleaser/goreleaser-action/blob/master/src/main.ts#L14-L21) when there is no git tag available.

**Comment by abatilo** [comment]
> Yes it's the right behavior. `goreleaser` requires a git tag to create a release and if we didn't force the snapshot mode in this action if no tag is found, the step would crash.

Checking for the existence of `GITHUB_REF` and checking that it starts with `refs/tags` doesn't seem like a reliable way to see whether or not there are any tags. Those checks are making the assumption that the event that triggers this action will have `refs/tags` in the `GITHUB_REF`, but that's not true. goreleaser will use the git metadata to grab the latest tag, even if `GITHUB_REF` doesn't start with `refs/tags`

**Comment by abatilo** [comment]
@crazy-max 
Ideally, you're checking the API to see if there are tags:
https://octokit.github.io/rest.js/#octokit-routes-repos-list-tags

Instead of relying on an unrelated environment variable.

**Comment by crazy-max** [comment]
Closing this issue (see [my comment](https://github.com/goreleaser/goreleaser-action/pull/29#issuecomment-548178809) about why).
