### ISSUE TITLE
Could you verify goreleaser action?

### ISSUE THREAD

**Issue by oNaiPs** [goreleaser/goreleaser-action#281]
Want to restrict my pipeline to verified actions but yours isn't. Documentation:

https://docs.github.com/en/developers/github-marketplace/applying-for-publisher-verification-for-your-organization

**Comment by crazy-max** [comment]
cc @caarlos0

**Comment by caarlos0** [comment]
not sure how to do it, as our action is not an oauth app...

![image](https://user-images.githubusercontent.com/245435/117980210-1a774100-b30a-11eb-9093-3eabbb1b9c3d.png)


any ideas @crazy-max?

**Comment by crazy-max** [comment]
@caarlos0 

> not sure how to do it, as our action is not an oauth app...

I think smth has to be done internally with GitHub Team. Keep you in touch!

**Comment by crazy-max** [comment]
[Done](https://github.com/marketplace/actions/goreleaser-action) :)

![image](https://user-images.githubusercontent.com/1951866/119883974-6d6b0e00-bf30-11eb-95cd-ef38110d8b5c.png)
