### ISSUE TITLE
Undocumented or incorrect prerelease behavior

### ISSUE THREAD

**Issue by displague** [goreleaser/goreleaser-action#303]
_(This is more or less a support question, but I am framing it as a documentation issue. Thanks for this awesome tool!)_

When I create a prerelease 'release' in the GH UI, goreleaser-action will unset the 'prerelease' flag. I then chase goreleaser by resetting the prerelease flag.

I see that there is some logic to detect prerelease tags in goreleaser, and I assume that if I follow this pattern or redefine this pattern, I should find goreleaser automatically flagging prereleases.

The documentation that I see today about GH prerelease is https://goreleaser.com/customization/release/ and https://goreleaser.com/customization/templates/.

Is it possible to define a matching prerelease pattern in goreleaser-action syntax? (my pattern is `v3.2.0-alpha.3`)
If this pattern is already in the default format, is there a bug in the handling?

This project is the GH Action project for goreleaser. PreRelease is one of ~five fields on the GH Release page.
Users would benefit from some documentation about this feature in the README.md if not elsewhere.

My build is using https://github.com/equinix/terraform-provider-metal/blob/88f7ef8/.github/workflows/release.yml#L39-L47

**Comment by crazy-max** [comment]
@displague I don't think GoReleaser is able to create a pre-release on GitHub. I think you should use `draft: true` in your config and when the release is created you just edit the draft and check pre-release in the UI. WDYT @caarlos0?

**Comment by caarlos0** [comment]
https://goreleaser.com/customization/release/

there is a `pre_release` option on the release config... maybe that's what you're looking for?

**Comment by crazy-max** [comment]
@caarlos0 Ah yes indeed!

**Comment by caarlos0** [comment]
closing as explained above.
