### ISSUE TITLE
goreleaser-action tries to download incorrect version of installer on armv6

### ISSUE THREAD

**Issue by tenyo** [goreleaser/goreleaser-action#308]
Hi, I'm trying to run gorelease-action on a 32-bit ARM machine (`armv6` arch) and it's trying to download `goreleaser_Linux_arm.tar.gz` which doesn't exist.

```
Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.180.3/goreleaser_Linux_arm.tar.gz
Error: Unexpected HTTP response: 404
```

The correct goreleaser binary in this case should be called `goreleaser_Linux_armv6.tar.gz` from looking at https://github.com/goreleaser/goreleaser/releases

**Comment by tenyo** [comment]
Guessing that the problem is again in https://github.com/goreleaser/goreleaser-action/blob/master/src/installer.ts#L50

**Comment by crazy-max** [comment]
Yes we don't handle arch variant atm.

**Comment by crazy-max** [comment]
@tenyo Can you try with `uses: goreleaser/goreleaser-action@master`?

**Comment by tenyo** [comment]
@crazy-max Thanks for the quick fix! It kinda worked but still failing in my case. 
I see it's correctly identifying the arch (`armv7`) but that version of goreleaser doesn't exist, there's only `armv6`. So, I guess, the question is, will the `goreleaser_Linux_armv6` binary work on armv7 (I would think so), in which case we can always download the `armv6` version?

```
> Run goreleaser/goreleaser-action@master
Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.180.3/goreleaser_Linux_armv7.tar.gz
Error: Unexpected HTTP response: 404
```

**Comment by caarlos0** [comment]
Yeah, just need to add to the config

**Comment by tenyo** [comment]
Thanks a lot guys! It downloads the correct version now after the last release which includes the v7 binary 🎉
