### ISSUE TITLE
Define permissions for the action

### ISSUE THREAD

**Issue by naveensrinivasan** [goreleaser/goreleaser-action#311]
GitHub recommends permissions for action https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/, this will reduce the attack vector.

The action should define default permission or provide recommendations as comments with the action.

**Comment by crazy-max** [comment]
This action itself does not require the `secrets.GITHUB_TOKEN`. I guess this secret is only used with the [`release`](https://goreleaser.com/customization/release/) creation by GoReleaser (cc @caarlos0).

**Comment by caarlos0** [comment]
Indeed @crazy-max is correct.

**Comment by caarlos0** [comment]
closing as explained above.

**Comment by hazcod** [comment]
Well yes, so it does need the `permissions` block since `release` is part of `goreleaser`?

**Comment by caarlos0** [comment]
I think

```yaml
permissions:
  contents: write
```

if you use the action token instead of a PAT
