### ISSUE TITLE
Using with cash action

### ISSUE THREAD

**Issue by tech10** [goreleaser/goreleaser-action#319]
I have attempted to use this with the cash action without success, but I don't know why, other than cash being unavailable across branches, perhaps, though I thought a tag wasn't specific to a branch at all. Here's my action configuration on a project that's been mostly dead for me since 2016, though I've used it for testing things like this.
https://github.com/tech10/teamtalk_bot/raw/master/.github/workflows/goreleaser.yml
Two workflow runs show that the cash is being saved with the same key twice, but was not restored on the second run after being saved on the first.

https://github.com/tech10/teamtalk_bot/actions/runs/1557024603
https://github.com/tech10/teamtalk_bot/actions/runs/1557043140

Does anyone have any suggestions, and perhaps an idea as to why this isn't working as I thought it would? My goal is to save time by cashing all go builds used by goreleaser, so they can be quickly reused and cut down on compile time for future releases. This would significantly reduce compile time, especially on projects releasing a vast number of compiled binaries.

**Comment by cristaloleg** [comment]
As I understood there was no changes in your `go.sum`, that's why cache key was the same, isn't this a case?

**Comment by tech10** [comment]
Yes, the hash remained the same across the two different releases, but it couldn't be retrieved the second time for some reason. I was never able to determine why this was.

**Comment by crazy-max** [comment]
@tech10 Looking at the events that trigger your workflow:

```yaml
on:
  push:
    tags:
      - 'v*'
```

It will only trigger when a tag is being pushed and as a tag is not tied to a branch, the cache' scope is not shared across other branches in your repository and therefore lost I think. As explained in the [README of actions/cache](https://github.com/actions/cache#cache-scopes):

> The cache is scoped to the key and branch. The default branch cache is available to other branches.

Therefore I think you have to also build against the default branch:

```yaml
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
```

If it still doesn't work, I suggest to open an issue on https://github.com/actions/cache instead as it's not directly related to the GoReleaser action.
