### ISSUE TITLE
Can not build with local sub module (No matching version for query "latest")

### ISSUE THREAD

**Issue by DblK** [goreleaser/goreleaser-action#320]
Hi,

I am new to `goreleaser` and it was working fine with my first version of messy code at root.
I started to create a new architecture for my code which is working fine locally.
I even tried `goreleaser` locally and everything works fine and release has been created.

However on GA it won't work. I have the following error:
```
go: finding module for package github.com/dblk/tinshop/gameid
github.com/dblk/tinshop/utils imports
	github.com/dblk/tinshop/gameid: no matching versions for query "latest"
```
You can find [my workflow here](https://github.com/DblK/tinshop/actions/workflows/goreleaser.yml) if it is helpful.

Did I miss something somewhere ?

**Comment by cristaloleg** [comment]
Looks like it's fixed, right?

**Comment by DblK** [comment]
Yep. It's fixed. I am closing it.
