### ISSUE TITLE
Default value in action

### ISSUE THREAD

**Issue by frank3950** [goreleaser/goreleaser-action#323]
how can i find all the default value of parameter when i didn't specify the .goreleaser.yml file in a github action?

**Comment by caarlos0** [comment]
you can run goreleaser locally with something `goreleaser release --rm-dist --skip-validate --skip-publish`, and it will generate a `dist/config.yaml` file with all the defaults

you can also see specific defaults in the documentation https://goreleaser.com/customization/

**Comment by frank3950** [comment]
oh thanks, that's a great help for me!
