### ISSUE TITLE
changelog only contains latest change

### ISSUE THREAD

**Issue by rsteube** [goreleaser/goreleaser-action#324]
Hi, sorry to bother you with this but i am not sure what is causing this.
I recently switched to the `goreleaser-action` and it seems the changelog now only contains the latest change:

https://github.com/rsteube/carapace-bin/releases/tag/v0.8.11

There should be more though:

https://github.com/rsteube/carapace-bin/compare/v0.8.10...v0.8.11

**Comment by caarlos0** [comment]
misconfiguration, please refer to https://goreleaser.com/errors/no-history/
