### ISSUE TITLE
go cross compilation

### ISSUE THREAD

**Issue by limz8319** [goreleaser/goreleaser-action#340]
Today I found an extra V1 in the output path
![RI0GO7KOie](https://user-images.githubusercontent.com/53548676/163723334-fccb8286-9b58-4cb9-87cf-515d6102c04a.jpg)
![aLZ4FYcdse](https://user-images.githubusercontent.com/53548676/163723340-4118caa6-03e5-4046-a083-a35d3933dacc.jpg)
Here is the previous output
![4PHFLfOwEN](https://user-images.githubusercontent.com/53548676/163723345-3b87797c-985f-4c30-b6f1-82925583682b.jpg)

**Comment by limz8319** [comment]
The output file path has an extra V1, resulting in the wrong path for docker build copy.

**Comment by caarlos0** [comment]
This is due to the goamd64 support, and is intended.

**Comment by limz8319** [comment]
```FROM alpine:latest
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

ARG TARGETARCH
WORKDIR /dist
ADD dist/gomain_linux_$TARGETARCH/main .
RUN apk add --no-cache tini
#http 和 grpc
EXPOSE 8080
ENTRYPOINT ["/sbin/tini", "--"]
#command 
CMD ["/bin/sh", "-c", "/dist/main serve"]
