### ISSUE TITLE
Windows binary signing issue via goreleaser 

### ISSUE THREAD

**Issue by georgettica** [goreleaser/goreleaser-action#361]
I got this error in GHA

https://github.com/georgettica/obnpctl/runs/6722829685?check_suite_focus=true
```
⨯release failed after 95.97serror=sign: cosign failed: exit status 1: Using payload from: dist/obnpctl_0.3.1_Windows_i386.tar.gz
Generating ephemeral keys...
Retrieving signed certificate...
Error: signing dist/obnpctl_0.3.1_Windows_i386.tar.gz: getting key from Fulcio: verifying SCT: unmarshal: unexpected end of JSON input
main.go:46: error during command execution: signing dist/obnpctl_0.3.1_Windows_i386.tar.gz: getting key from Fulcio: verifying SCT: unmarshal: unexpected end of JSON input
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.6.3/x64/goreleaser' failed with exit code 1
```
Also I saved the log:
[logs_760.zip](https://github.com/goreleaser/goreleaser-action/files/8833361/logs_760.zip)

The goreleaser file is in https://github.com/georgettica/obnpctl/blob/main/.goreleaser.yaml

This started to happen recently, and I am not sure what is the source of it.
I can dig deeper in the goreleaser code but wanted to surface it here first 

---
The issue inhibits Linux binaries which are required for this release

**Comment by caarlos0** [comment]
that error is from cosign, you might need to open an issue there.
