### ISSUE TITLE
syft not found

### ISSUE THREAD

**Issue by 06kellyjac** [goreleaser/goreleaser-action#362]
when using the sbom output goreleaser needs syft in the PATH

either goreleaser-action should fetch syft, or there should be documentation around how syft should be added before the goreleaser-action is ran

**Comment by caarlos0** [comment]
nor goreleaser or goreleaser action install any dependencies.

You can install syft using their action documentation: https://github.com/anchore/sbom-action/

**Comment by 06kellyjac** [comment]
> or there should be documentation

Just documentation around the sub action would have avoided this

**Comment by 06kellyjac** [comment]
Amazing. Many thanks
