### ISSUE TITLE
How to re-run without re-releasing?

### ISSUE THREAD

**Issue by mholt** [goreleaser/goreleaser-action#371]
Hi, we're trying to release Caddy v2.6.1 but the release job failed because a binary took more than 30m to build (I noticed it running pretty slowly today in general):

https://github.com/caddyserver/caddy/actions/runs/3100438200/jobs/5020719987

I'm wondering how we can:

1) Remove or extend the timeout
2) Re-run the release job without re-releasing

I'm not very well versed in GitHub actions / goreleaser so I thought I'd ask here. Thanks for any advice!

Here's our release script: https://github.com/caddyserver/caddy/blob/master/.github/workflows/release.yml

**Comment by mholt** [comment]
Wait, @Mohammed90 just clued me in that GitHub now has a "Re-run jobs" button. And that it should be safe to re-run release jobs.

We're trying that now. If that works, ignore question 2. :smile: Still wondering about that timeout option though!

**Comment by caarlos0** [comment]
Hey @mholt !

> * Remove or extend the timeout

there's a timeout flag in the release command: https://goreleaser.com/cmd/goreleaser_release/

I'm not aware if github actions et al have a timeout as well though...

> * Re-run the release job without re-releasing

yep, just re-run the job in the github actions UI, it should work :)

**Comment by mholt** [comment]
Thank you so much, it wasn't clear to me how to set that in the action.

Thanks for GoReleaser!
