### ISSUE TITLE
Supprt tags in sub ref directory?

### ISSUE THREAD

**Issue by wxiaoguang** [goreleaser/goreleaser-action#380]
The code says:

https://github.com/goreleaser/goreleaser-action/blob/b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757/src/git.ts#L19-L24

If `GITHUB_REF=refs/tags/release/0.1.0`, then the `tag` will be `0.1.0`, but it should be `release/0.1.0`

Is the `pop` done by purpose? Could it support `release/0.1.0` and use `0.1.0` as the version?

**Comment by caarlos0** [comment]
this whole thing should probably be removed, probably, as goreleaser itself already handles it

https://github.com/goreleaser/goreleaser-action/pull/370

cc/ @crazy-max

**Comment by wxiaoguang** [comment]
Thank you for your quick response.

IMO #370 is not enough. There is also a check like `isTagDirty = git.isTagDirty(git.getTag())`
https://github.com/goreleaser/goreleaser-action/blob/b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757/src/main.ts#L31-L33


Then, `release/0.1.0` will case error `No tag found for commit aabbccdd. Snapshot forced` and then the `--snapshot` will be applied (incorrectly).

https://github.com/goreleaser/goreleaser-action/blob/b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757/src/main.ts#L49-L53

**Comment by caarlos0** [comment]
hmm, indeed... @crazy-max probably we should remove those and bump the action to v4...

**Comment by crazy-max** [comment]
Hum I see yeah we might need a major bump.

**Comment by caarlos0** [comment]
should be fixed in #370 
will release soon

**Comment by wxiaoguang** [comment]
But the bug is in https://github.com/goreleaser/goreleaser-action/blob/b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757/src/git.ts#L19-L24

?


It will return an incorrect tag to  `tag`, then `isTagDirty(tag)` will trigger an error inside and return `true`, then the `--snapshot` will be applied to the command argument?

**Comment by caarlos0** [comment]
ah sorry, the dirty thing is still there.

**Comment by caarlos0** [comment]
#382 should fix it by removing it entirely.
