### ISSUE TITLE
goreleaser source archive no longer formatting .gitattributes export-subst correctly

### ISSUE THREAD

**Issue by dopey** [goreleaser/goreleaser-action#406]
https://github.com/smallstep/certificates/issues/1277

About 6 months we bumped from goreleaser 2.x to 3.x in our github actions. Around the same time (I can't actually confirm because our Github Actions logs don't go back far enough) the .VERSION file that is meant to be re-formatted automatically when `git archive` is run on the repo stopped working. This used to be the way we were able to get the correct version from our goreleaser generated source code archives (because the git tree doesn't exist in source archives).

Here's the .VERSION file which used to be overwritten during a `git archive`: https://github.com/smallstep/certificates/blob/818dffe6fea9cf2fd0b38ff5c4b60b8da721b02b/.VERSION
The .gitattributes file instructing `git archive` which areas to substitute: https://github.com/smallstep/certificates/blob/818dffe6fea9cf2fd0b38ff5c4b60b8da721b02b/.gitattributes
And finally, the source stanza in our goreleaser config: https://github.com/smallstep/certificates/blob/master/.goreleaser.yml#L80-L83

**Comment by caarlos0** [comment]
it should be fixed on latest goreleaser (v1.17.0), there is a test enforcing it now https://github.com/goreleaser/goreleaser/blob/b36e30a071199b7290b73b3faa0652825c4d88fc/internal/pipe/sourcearchive/source_test.go#L33
