### ISSUE TITLE
How can i specific file into released archive file

### ISSUE THREAD

**Issue by NoahAmethyst** [goreleaser/goreleaser-action#409]
To be honest goreleaser is a wonderful project.

I found that every archived file include go executable file and README.md

What if i want specific other file that exist in my repository into released archive file, how can i do that?

**Comment by caarlos0** [comment]
you can create a yaml config file, and set up the archives however you want: https://goreleaser.com/customization/archive/

https://goreleaser.com/intro

**Comment by NoahAmethyst** [comment]
> 

Thank you for your answer :)
