### ISSUE TITLE
latest reports the previous version

### ISSUE THREAD

**Issue by jzelinskie** [goreleaser/goreleaser-action#416]
We're running with the action configured to latest -- it's running fine, but outputting this:

```running goreleaser v1.18.2-pro (outdated, latest is v1.18.1-pro)```

Here's an example job: https://github.com/authzed/spicedb/actions/runs/4951374935/jobs/8856253681

**Comment by caarlos0** [comment]
will be fixed in the next version, thanks for reporting 🙏
