### ISSUE TITLE
Add config file to GitHub action

### ISSUE THREAD

**Issue by SpotlightForBugs** [goreleaser/goreleaser-action#426]
I want to customise the config, but there seems no way to do that...

**Comment by caarlos0** [comment]
You mean the goreleaser config file?

Add to the root of your repo as usual and it should just work.

If you have the file in a different path or name, you can pass the path in the `args` option.

**Comment by SpotlightForBugs** [comment]
> You mean the goreleaser config file?
> 
> 
> 
> Add to the root of your repo as usual and it should just work.
> 
> 
> 
> If you have the file in a different path or name, you can pass the path in the `args` option.
> 
> 
> 
> 

You are right!
Thanks
