### ISSUE TITLE
Release Failure with Official Versions using GoReleaser Action v4

### ISSUE THREAD

**Issue by cubxxw** [goreleaser/goreleaser-action#445]
I'm encountering an issue with GoReleaser Action v4 when releasing different types of versions. Pre-releases like `v3.5.1.beta.0` are successfully published, but official releases (e.g., `v3.5.1`) fail.

Error encountered: 

```
"failed to upload artifact... error=POST https://uploads.github.com/repos/***sdk/chat/releases/135400526/assets?name=chat_1.5.1-rc.0_linux_ppc64le.pkg.tar.zst: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]"
```

Complete error log available at: https://github.com/openimsdk/chat/actions/runs/7364259821/job/20044473138

It seems like there's an issue with asset uploading for official releases. Pre-release assets upload without problems. Any insights or solutions would be greatly appreciated.

Thanks!

**Comment by cubxxw** [comment]
@crazy-max

**Comment by caarlos0** [comment]
You are likely running the release two times concurrently when a tag is created

**Comment by caarlos0** [comment]
Oh, my bad, it's something with tag sorting, it tried to release rc0 again

Changing git.tag_sort should help 

https://goreleaser.com/customization/git/

**Comment by cubxxw** [comment]
Certainly, thank you for your assistance. I will now proceed to give it a try.
