### ISSUE TITLE
Github: release notes no longer generated

### ISSUE THREAD

**Issue by andig** [goreleaser/goreleaser-action#447]
Github seems to have introduced a new feature that forces the user to write or generate release notes before starting the build.

In my case- https://github.com/evcc-io/evcc/releases/tag/0.124.0- that lead to the goreleaser action not overwriting these already filled release notes.

Unfortunately, the GH-generated notes are lacking the goreleaser features like e.g. skipping certain PRs.

**Comment by caarlos0** [comment]
I did some releases early today and had no issues with it...

FWIW, to force replace existing release notes, set `release.mode: replace`

https://goreleaser.com/customization/release/

**Comment by andig** [comment]
Closing since I can customize the override# thank you!
