### ISSUE TITLE
release flag doesn't work `--release-header`

### ISSUE THREAD

**Issue by tsaikat** [goreleaser/goreleaser-action#452]
When i use this flag as string it tries to open it as a file and fails.
using it like `release --release-header="##Release" --clean --verbose`
```
generating changelog
    • loading file "## Release"
  ⨯ release failed after 43s                 error=open ## Release: no such file or directory
```
  
 But when i use it with release-notes somehow it works fine 
 `release -release-notes=CHANGELOG.md --release-header="## Release" `

**Comment by caarlos0** [comment]
as pointed out in the docs and `goreleaser release --help`, that flags needs to point out to a file

https://goreleaser.com/cmd/goreleaser_release/?h=release
