### ISSUE TITLE
failed with error `error=only configurations files on version: 2 are supported, yours is version: 0, please update your configuration`

### ISSUE THREAD

**Issue by zhuwenxing** [goreleaser/goreleaser-action#466]
goreleaser.yaml: https://github.com/zhuwenxing/milvus-backup/blob/main/.goreleaser.yaml

workflow: https://github.com/zhuwenxing/milvus-backup/blob/main/.github/workflows/release.yaml

failed job: https://github.com/zhuwenxing/milvus-backup/actions/runs/9509999157/job/26213818249

**Comment by zhuwenxing** [comment]
fixed by adding `version: 2` in goreleaser.yaml

**Comment by caarlos0** [comment]
it'll only fail with that error if the configuration is invalid, so probably you had another property you needed to update as well.
