### ISSUE TITLE
Cannot find GoReleaser release 2.1.0 in https://goreleaser.com/static/releases.json

### ISSUE THREAD

**Issue by twpayne** [goreleaser/goreleaser-action#469]
Title says it all.

The action is currently failing with the above error message.

See, for example: https://github.com/twpayne/chezmoi/actions/runs/9928048276/job/27429277114

Refs https://github.com/twpayne/chezmoi/pull/3867.

**Comment by caarlos0** [comment]
oh, good find!

reason: https://github.com/goreleaser/goreleaser/actions/runs/9921903807/attempts/1

**Comment by caarlos0** [comment]
thanks for reporting this, and sorry for the trouble. hopefully this is fixed for good now.

https://github.com/goreleaser/goreleaser/commit/c3ea906db834a7c9fc3f189537f9cbe741243bd6

**Comment by twpayne** [comment]
Confirmed, thanks! https://github.com/twpayne/chezmoi/actions/runs/9928048276/job/27431676263?pr=3867

Thank you for the very speedy fix!
