### ISSUE TITLE
bug SQLLite compilation error

### ISSUE THREAD

**Issue by YouChenJun** [goreleaser/goreleaser-action#472]
When my code used sqllite, compilation was normal, but there was an error when using the compiled binary file
![image](https://github.com/user-attachments/assets/074b0a15-c5e6-4aa8-8551-99a5114b6cf6)
Here is my profile information
![image](https://github.com/user-attachments/assets/5a1f361c-9555-484c-8df9-ebd6a0747bb9)
I also checked if 'CGO-ENABLED=1'
![image](https://github.com/user-attachments/assets/ab989a20-29e0-4807-b0eb-c208992065a9)

**Comment by caarlos0** [comment]
this is not a bug.

you need to set up your goreleaser configuration properly.

https://goreleaser.com/customization/
