### ISSUE TITLE
Should do nothing when not a tag commit?

### ISSUE THREAD

**Issue by andreynering** [goreleaser/goreleaser-action#61]
Hi there,

I recently started using this action and it works great. Thanks for it!

But I noted that it always try to build even if the current commit is not a tag (it uses `--snapshot` in this case). While that may be useful to test the process, I think it's waste of resources and should be disabled most of the time.

IMO the ideal scenario would be to only run when a new tag is pushed. Unfortunately, seems that such event doesn't exist: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows

So perhaps it would be just better to just return and do nothing when not a tag? I think this probably should be the default, and we'd have an argument to always run the build. If you disagree, we could at least have an argument to skip the build when not a tag.

Opinions?

**Comment by crazy-max** [comment]
Hi @andreynering,

> But I noted that it always try to build even if the current commit is not a tag (it uses --snapshot in this case).

Yes that's on purpose if the workflow is not triggered on push tag.

> IMO the ideal scenario would be to only run when a new tag is pushed. Unfortunately, seems that such event doesn't exist

I have not tested it myself but I think you can trigger a workflow only on push tag with this event:

```
on:
  push:
    tags:
      - '*'
```

If it doesn't work, you can try this:

```
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "::warning::Not a tag, skipping..."
            exit 1
          fi
```

> So perhaps it would be just better to just return and do nothing when not a tag?

I prefer to keep it this way if users want to push snapshot release as [GitHub Artifact](https://github.com/marketplace/actions/upload-artifact) for testing purpose. This is useful if a PR is created and we want to test it right away.

**Comment by andreynering** [comment]
@crazy-max 

> I have not tested it myself but I think you can trigger a workflow only on push tag with this event:
> 
> ```
> on:
>   push:
>     tags:
>       - '*'
> ```

That worked like a charm, thanks!

I'm fine with keeping things as is, then. I think it'd be nice to mention this possibility in the README or the documentation, though.

**Comment by crazy-max** [comment]
@andreynering 

> I'm fine with keeping things as is, then. I think it'd be nice to mention this possibility in the README or the documentation, though.

Done

**Comment by andreynering** [comment]
@crazy-max Thank you!
