### ISSUE TITLE
goreleaser: error: unknown long flag '--snapshot', try --help

### ISSUE THREAD

**Issue by dzpao** [goreleaser/goreleaser-action#94]
The github actions are broken.

See also:
https://github.com/mudclient/go-mud/runs/436203136?check_suite_focus=true#step:5:26

workflow:
https://github.com/mudclient/go-mud/actions/runs/37026103/workflow

config file:
https://github.com/mudclient/go-mud/blob/6ca1a37198db52f41ed1bbf6983a0e8b2540fadf/.goreleaser.yml

It looks like goreleaser-action adds parameters that should not be added when calling goreleaser.

**Comment by crazy-max** [comment]
Hi @dzpao,

That's because `goreleaser check` used [here in your workflow](https://github.com/mudclient/go-mud/runs/436203136?check_suite_focus=true#step:5:23) does not implement `--snapshot` flag.

**Comment by dzpao** [comment]
Thank you for your reply.
So what should I do? I noticed that the goreleaser and goreleaser-action I used are both the latest version.

**Comment by crazy-max** [comment]
@dzpao This is a limitation with this action. When I set it up, I hadn't thought about other use cases other than the `release` command. Keep you informed in the most appropriate way for your use case.

**Comment by crazy-max** [comment]
@dzpao Latest release should fix your issue.
